volumes:
  node_modules:
  ollama_data:

services:
  backend:
    build:
      context: .
      dockerfile: backend/.docker/Dockerfile
    container_name: django_llm_app
    volumes:
      - ./backend:/app
    ports:
      - "8888:8888"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    container_name: frontend_llm_app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3333:3333"

  llm:
    image: ollama/ollama:latest
    container_name: llm_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
